travis:
  secure:
    BINSTAR_TOKEN: mtJE86ZRX5hNr27LszxQFW750ZCnAaz7DgchSIqSSqMX+ehrj6xMgUK/4OfiDDiQ5o/qDjeKuo0cgSoecvAgKbrJ/ASV4Cp/qqobja1w5C2QipzZbiaIsbK6AIUwVZRyOmPik79T13w8JPq9OYEnSf4qbZ33q1HV7NDWm1Y4bt+Fifup/KPpTqOxcjzW92smvR4RJeIEqJbYloKV4baHyaWIpHHl3ZFnw1wygJQaB2MkMIsiQr/8PmHJ4n2t0mNM4zp0MQrx6jWbzfp95NOsmW43iv0hnUBYZUl9CiHaN8BmhmfDSFUNBOHuyKDnWYmw5V8bWh3HkN6X5XGa38m2rRJrriJKEHt4Pj57Zf+Xook93H9EmLxqkiAR2NTammlFIGsAhmchY6qHXCVElla4awpqB6XG6DsjMZD+9l/0QpmqvdmEtddx1uct3rUV6VTS5ikTRswxYZUcbjAR9qm+8yPFCyh6N1r+nq9jXipauc81Q82ihrMWTXYQEclQSd0pyonP3X2/IM26pB5MAZaMlpDLVGMFmRQFMLzLyO4Iq5K8GEUA4TNGOJ3l/0jt4DwWLlUGwmubomVyVfXd1njzb9n8NlJU1bzmeRd2x8knE/C2sm+sbl6R0MukH+KG2XV7ui/64UQ4JqLIOWhcVZt6YfTNhcMOBHrO3CyYws6/n6E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
