travis:
  secure:
    BINSTAR_TOKEN: APU/z1Zacl+XAwCQNykD5EB1TXwU6ZrAKTtFbPVwItrmFxmxAI0ecKsUFzzfXbs8yQ1G6FmLdppIV52O7sILsFx5nRTxt87UwXQHWVi70usP7zCu5KUXvlFzDq8ELo1afuH6Is7QA5GfAf6U3/mvi15GGc3tOxzvDl7W/iPPeSz2tcwEujtza/9WisHhP15KcCfS+kJqvhohfyCAH9X4crv81kKdus+4hf4NFvLaZ2MFpTLFDTL6lbsLmQ1Riq/q1G+kZcBJK5ss4ZyU/Gfu0cFvMrvYDr8E/KXQfIUNlSmN1s9oiYXx0j2jFtuo1aL6wEztO75/K08bGrmyLcLvuPykkJef82sxmQa2vpWUNQw0E/pZFMmCA6C1pl42f78ZkxJq2fnQy3QzheFnC69Unqh0ALF6PlDrTvzzjfPuXRyyOuyLc6O7SQR3Ih+A8axlSLEuXLUKCdn7guqAGTQXMx7ZkHgAehYC5WWYFUJQTjjLjnWHB0PL4TkeiNxlOYGT71l8rUziP7wZUlQq/DuoQ/vzYNkwNzF0jlPenxm4pO3TJD0EAIF0/1UUiMHlATWzKni9WMfuHl0cAYEiN+BVc0BN/0OYuhKMzatkEz1U3bYGjAZCCnoDBPHtdYla2vJACPd+inwQ/3rDi0GKisoyxRFcpH5LgcmLZQXLafq/7q8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
