travis:
  secure:
    BINSTAR_TOKEN: gHtzaRqhPLjlcvXS6VzeZ+vDkojMRn5ybIAJJnw7rI3htYD4QwZBYXbsf8Q0Dmu1FznOtv8G7oH0o4/0XnFshpUHzWxFjmJEuKghtpn581YgnySNIvi3pSgZ9pABKewapOEjV8rLQPgHK+YoIdnDWSG8GMGoF7uOjoMZt4XkymhKNFXS3m8B6DFiX8LzLc0Gc4zK1bYaOmV97Ju5OLbm4Vq+zbDdz89mAwMp3nSAxEgQ9YuLLY2/Sk6dxCHjfhtFmywfCjAe0vjQcauUuTm6dQWgPUIcC27QFFuPDcAG41j77HvzNpVZs3DsPB1uidXwplC+XzG7qEfqQ2+azUvdr7SEEpr+tCvF7sFZ/4aw6rBP2dRySgBmGuQ6x2hUOEF8dNAzIBvw1L2aytw3ag5u1GmSq5yY1v9aQ4YOeJsP5+G50E4/zDPsRGcC2eE2rdn2RqjXxilrTkZHlg9Qf2QRDjMbVQqliETEIYomuUUIiHNsP5HAZDg8mOsRMzQ6pBKIHIvhveuRiT+9+MkPpyog4Bgon7rYRwYiHyPCGc3j2VM8G5DX/F5jHJnbTIirmOH26c0raP28WSN4gCUd/vhUsSudxXzQXT7wDL0f8yxzL9eoAnsu3ZZZ7HdYpeLM2S9BYLjpFAz9K3PtxNM5iglI0uJaINHCkpf2se/yU4PC9Tc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
