travis:
  secure:
    BINSTAR_TOKEN: KYhkHjOaj/LRZN90f9ukQkU4toknFL1p4t4PlbHvoTiPYVTWXHBfZ55nZtLYn8jUhzbtxd+mlDUu2jz/0OktvS/ThxpU0TllpHq8gowkeF3qPELiJHUv10qitXlJA5agWWJYPLHOeap9wli+NvtkgeS3IFs2mHUKctK/v0sczmlsnKn5ei0GfzQ6/R3eB2NatCn90FQtai9jRoZ60x+VULOdcO1MCl2jnfytSqYRjq/JCQtzbNFBEqQzTT8qOfQlVplMKPk4qOA1y61nits4CJVB/KmmPMaFQcyiAwuigw8KvV/EJROPUE83Eq6YtVv+goZAFB9yWVSRsZJXnJJXJxB1egOG6u/9UkNj6LqxYeU3EpPca+rRYsrmCqBpKfJqcj9xa5LZEkIYJqfrF07wGydQBs1RS0lUv7V/YMobzO3Ui01AhB2RYCWecDIY3zxIRTM3/76JUbm3JSFLRTa0rG9W6LDq4UkDbxV4lBDFX0CrVYwSkHpkcneTBxsJ3XqmsAIFAAcpAge5lJQMl4cT29ht3xdZhBcPorGrFL0JoUFnOU/cpPPoQKHW8HYkAL5oqT4oT82GXxBoZEyWCkjtV/8pfyKo6kxlUafZeCnjaMUxVx6qt2vUFlF7ogRLXGs2fP2f8YOne7vMZgfY7cbnadGWTRvRrYyuc6TwoXyh79k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
